Repository asdvsvs/ddarelro, pull requests merged in 2023-12, with the labels that each got.

#9 Feat/comment 댓글 기능 구현
  src/main/java/com/b3/ddarelro/domain/comment/controller/CommentController.java
  src/main/java/com/b3/ddarelro/domain/comment/dto/CommentListReq.java
  src/main/java/com/b3/ddarelro/domain/comment/dto/CommentListRes.java
  src/main/java/com/b3/ddarelro/domain/comment/dto/request/CommentCreateReq.java
  src/main/java/com/b3/ddarelro/domain/comment/dto/request/CommentUpdateReq.java
  src/main/java/com/b3/ddarelro/domain/comment/dto/response/CommentCreateRes.java
  src/main/java/com/b3/ddarelro/domain/comment/dto/response/CommentDeleteRes.java
  src/main/java/com/b3/ddarelro/domain/comment/dto/response/CommentUpdateRes.java
  src/main/java/com/b3/ddarelro/domain/comment/entity/Comment.java
  src/main/java/com/b3/ddarelro/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/b3/ddarelro/domain/comment/repository/CommentRepository.java
  src/main/java/com/b3/ddarelro/domain/comment/service/CommentService.java
  src/main/java/com/b3/ddarelro/global/config/JpaConfig.java
  src/main/java/com/b3/ddarelro/global/exception/GlobalException.java
Labels: enhancement

#15 Feat/Card
  src/main/java/com/b3/ddarelro/domain/card/controller/CardController.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardCreateReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardDeleteReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardDueDateReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardModifyReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardCreateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardDeleteRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardDueDateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardListRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardModifyRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/exception/CardErrorCode.java
  src/main/java/com/b3/ddarelro/domain/card/repository/CardRepository.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardRepository.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
  src/main/java/com/b3/ddarelro/global/config/MockSpringSecurityFilter.java
Labels: enhancement

#22 [#5] feat: Card 마감일자 지정 구현
  src/main/java/com/b3/ddarelro/domain/card/controller/CardController.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardDueDateReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardDueDateRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
Labels: enhancement

#29 컬럼 soft delete, restore 기능 구현
  src/main/java/com/b3/ddarelro/domain/column/controller/ColumnController.java
  src/main/java/com/b3/ddarelro/domain/column/dto/request/ColumnRestoreReq.java
  src/main/java/com/b3/ddarelro/domain/column/dto/response/ColumnRestoreRes.java
  src/main/java/com/b3/ddarelro/domain/column/entity/Column.java
  src/main/java/com/b3/ddarelro/domain/column/repository/ColumnRepository.java
  src/main/java/com/b3/ddarelro/domain/column/service/ColumnDeleteRestoreService.java
  src/main/java/com/b3/ddarelro/domain/column/service/ColumnService.java
Labels: enhancement

#32 컬럼 버그 수정
  src/main/java/com/b3/ddarelro/domain/column/dto/response/ColumnsGetRes.java
  src/main/java/com/b3/ddarelro/domain/column/repository/ColumnRepository.java
  src/main/java/com/b3/ddarelro/domain/column/service/ColumnService.java
Labels: bug

#33 [#5] Feat/card delete
  src/main/java/com/b3/ddarelro/domain/card/controller/CardController.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardListReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardCreateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardDueDateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardListRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardModifyRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/repository/CardRepository.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardDeleteRestoreService.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
Labels: enhancement

#35 [#5] Refactor/get card list
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardCreateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardDueDateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardListRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardModifyRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/repository/CardRepository.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardDeleteRestoreService.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
Labels: refactored

#37 User 조회/수정 구현
  src/main/java/com/b3/ddarelro/domain/user/controller/UserController.java
  src/main/java/com/b3/ddarelro/domain/user/dto/request/UserPasswordUpdateReq.java
  src/main/java/com/b3/ddarelro/domain/user/dto/request/UsernameUpdateReq.java
  src/main/java/com/b3/ddarelro/domain/user/dto/response/UserLoginRes.java
  src/main/java/com/b3/ddarelro/domain/user/dto/response/UserPasswordUpdateRes.java
  src/main/java/com/b3/ddarelro/domain/user/dto/response/UserRes.java
  src/main/java/com/b3/ddarelro/domain/user/dto/response/UsernameUpdateRes.java
  src/main/java/com/b3/ddarelro/domain/user/entity/User.java
  src/main/java/com/b3/ddarelro/domain/user/exception/UserErrorCode.java
  src/main/java/com/b3/ddarelro/domain/user/service/UserService.java
  src/main/java/com/b3/ddarelro/global/security/JwtAuthenticationFilter.java
  src/main/java/com/b3/ddarelro/global/security/JwtAuthorizationFilter.java
  src/main/resources/application.yml
Labels: enhancement, refactored

#39 파일 API구현
  build.gradle
  src/main/java/com/b3/ddarelro/domain/board/entity/Board.java
  src/main/java/com/b3/ddarelro/domain/board/service/BoardService.java
  src/main/java/com/b3/ddarelro/domain/file/controller/FileController.java
  src/main/java/com/b3/ddarelro/domain/file/dto/FileListReq.java
  src/main/java/com/b3/ddarelro/domain/file/dto/request/FileUploadReq.java
  src/main/java/com/b3/ddarelro/domain/file/dto/response/FileDeleteRes.java
  src/main/java/com/b3/ddarelro/domain/file/dto/response/FileDownloadRes.java
  src/main/java/com/b3/ddarelro/domain/file/dto/response/FileListRes.java
  src/main/java/com/b3/ddarelro/domain/file/dto/response/FileUploadRes.java
  src/main/java/com/b3/ddarelro/domain/file/entity/File.java
  src/main/java/com/b3/ddarelro/domain/file/exception/FileErrorCod.java
  src/main/java/com/b3/ddarelro/domain/file/repository/FileRepository.java
  src/main/java/com/b3/ddarelro/domain/file/service/FileDeleteRestoreService.java
  src/main/java/com/b3/ddarelro/domain/file/service/FileService.java
  src/main/java/com/b3/ddarelro/global/config/S3Config.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: enhancement

#42 [#5] Feat/card restore
  src/main/java/com/b3/ddarelro/domain/card/controller/CardController.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardDueDateReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardMoveReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardRestoreReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardMoveRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardRestoreRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/exception/CardErrorCode.java
  src/main/java/com/b3/ddarelro/domain/card/repository/CardRepository.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
Labels: enhancement, refactored
