Repository asdvsvs/ddarelro, pull requests merged in 2024-01, with the labels that each got.

#49 이메일 인증 구현 및 Redis 연결
  build.gradle
  src/main/java/com/b3/ddarelro/domain/user/controller/EmailController.java
  src/main/java/com/b3/ddarelro/domain/user/dto/request/EmailAuthSendReq.java
  src/main/java/com/b3/ddarelro/domain/user/dto/request/EmailCodeCheckReq.java
  src/main/java/com/b3/ddarelro/domain/user/dto/response/EmailAuthSendRes.java
  src/main/java/com/b3/ddarelro/domain/user/dto/response/EmailCodeCheckRes.java
  src/main/java/com/b3/ddarelro/domain/user/entity/EmailAuth.java
  src/main/java/com/b3/ddarelro/domain/user/entity/User.java
  src/main/java/com/b3/ddarelro/domain/user/entity/UserStatus.java
  src/main/java/com/b3/ddarelro/domain/user/exception/EmailErrorCode.java
  src/main/java/com/b3/ddarelro/domain/user/repository/EmailAuthRepository.java
  src/main/java/com/b3/ddarelro/domain/user/repository/UserRepository.java
  src/main/java/com/b3/ddarelro/domain/user/service/EmailAuthService.java
  src/main/java/com/b3/ddarelro/domain/user/service/EmailService.java
  src/main/java/com/b3/ddarelro/domain/user/service/UserService.java
  src/main/java/com/b3/ddarelro/global/config/EmailConfig.java
  src/main/java/com/b3/ddarelro/global/config/RedisConfig.java
  src/main/java/com/b3/ddarelro/global/config/WebSecurityConfig.java
  src/main/java/com/b3/ddarelro/global/email/EmailUtil.java
  src/main/java/com/b3/ddarelro/global/security/JwtAuthorizationFilter.java
  src/main/java/com/b3/ddarelro/global/security/UserDetailsImpl.java
  src/main/java/com/b3/ddarelro/global/security/UserDetailsServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/email.html
  src/test/java/com/b3/ddarelro/domain/board/BoardIntegrationTest.java
  src/test/resources/application.yml
Labels: enhancement, refactored

#48 Refactor - Controller단 코드 리팩토링
  src/main/java/com/b3/ddarelro/domain/card/controller/CardController.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardWorkersReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardCreateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardDueDateRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardModifyRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardRes.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardWorkersRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
  src/main/java/com/b3/ddarelro/domain/worker/entity/Assignment.java
  src/main/java/com/b3/ddarelro/domain/worker/entity/Worker.java
  src/main/java/com/b3/ddarelro/domain/worker/repository/WorkerRepository.java
Labels: refactored

#54 RefreshToken 구현
  src/main/java/com/b3/ddarelro/domain/user/entity/EmailAuth.java
  src/main/java/com/b3/ddarelro/global/config/WebSecurityConfig.java
  src/main/java/com/b3/ddarelro/global/jwt/RefreshToken.java
  src/main/java/com/b3/ddarelro/global/jwt/TokenProvider.java
  src/main/java/com/b3/ddarelro/global/jwt/exception/TokenErrorCode.java
  src/main/java/com/b3/ddarelro/global/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/b3/ddarelro/global/jwt/service/TokenService.java
  src/main/java/com/b3/ddarelro/global/security/JwtAuthenticationFilter.java
  src/main/java/com/b3/ddarelro/global/security/JwtAuthorizationFilter.java
  src/main/java/com/b3/ddarelro/global/security/UserDetailsServiceImpl.java
Labels: enhancement, refactored

#55 [#47] Card에 작업자 할당
  src/main/java/com/b3/ddarelro/domain/card/controller/CardController.java
  src/main/java/com/b3/ddarelro/domain/card/dto/request/CardWorkersReq.java
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardWorkersRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/exception/CardErrorCode.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
  src/main/java/com/b3/ddarelro/domain/worker/entity/Assignment.java
  src/main/java/com/b3/ddarelro/domain/worker/entity/Worker.java
  src/main/java/com/b3/ddarelro/domain/worker/repository/WorkerRepository.java
Labels: enhancement

#58 [#56] refactor: Card조회시 할당된 작업자들 보이게
  src/main/java/com/b3/ddarelro/domain/card/dto/response/CardRes.java
  src/main/java/com/b3/ddarelro/domain/card/entity/Card.java
  src/main/java/com/b3/ddarelro/domain/card/service/CardService.java
  src/main/java/com/b3/ddarelro/domain/worker/WorkersRes.java
Labels: enhancement

#57 컬럼 단위 테스트 코드 구현
  src/main/java/com/b3/ddarelro/domain/column/dto/request/ColumnCreateReq.java
  src/main/java/com/b3/ddarelro/domain/column/dto/request/ColumnDeleteReq.java
  src/main/java/com/b3/ddarelro/domain/column/dto/request/ColumnGetReq.java
  src/main/java/com/b3/ddarelro/domain/column/dto/request/ColumnMoveReq.java
  src/main/java/com/b3/ddarelro/domain/column/dto/request/ColumnRestoreReq.java
  src/main/java/com/b3/ddarelro/domain/column/dto/request/ColumnUpdateReq.java
  src/main/java/com/b3/ddarelro/domain/column/service/ColumnService.java
  src/test/java/com/b3/ddarelro/domain/column/ColumnCommonTest.java
  src/test/java/com/b3/ddarelro/domain/column/controller/ColumnControllerTest.java
  src/test/java/com/b3/ddarelro/domain/column/repository/ColumnRepositoryTest.java
  src/test/java/com/b3/ddarelro/domain/column/service/ColumnServiceTest.java
Labels: Test
